# fly.toml app configuration file generated for vibefenwei on 2023-08-20T13:35:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vibefenwei"
primary_region = "lax"

[build]

[env]
  HOST = "https://vibefenwei.fly.dev/"
  NODE_ENV = "production"
  PORT = "8081"
  SCOPES = "write_products,read_content,write_content"
  SHOPIFY_API_KEY = "f844c74769e61de9647977a2ed79bd3d"
  SHOPIFY_API_SECRET = "87fd6b6d808b66234e300255fec6263b"
  OPEN_AI_SECRET_KEY= "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"
  REDIS_API_PASSWORD= "au34F3z3Bn8izOjWQ9zPITaQ6MYTE3CP"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
