# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-neuralnectar"
client_id = "b2919712bc4555c05f978c56eb4f5750"
application_url = "https://passport-remember-integrated-dependent.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content"

[auth]
redirect_urls = [
  "https://passport-remember-integrated-dependent.trycloudflare.com/auth/callback",
  "https://passport-remember-integrated-dependent.trycloudflare.com/auth/shopify/callback",
  "https://passport-remember-integrated-dependent.trycloudflare.com/api/auth/callback",
  "https://passport-remember-integrated-dependent.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
# dev_store_url = "quickstart-b80cd149.myshopify.com"
